# Generated by Django 4.2.1 on 2023-05-27 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_rate', models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('salary', 'Salary')], max_length=100)),
                ('debts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('down_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_type', models.CharField(choices=[('FHA', 'FHA'), ('Conventional', 'Conventional')], max_length=100)),
                ('mi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Upfront_Mi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condo_fee_hoa', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Condo Fee/HOA')),
                ('insurance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('term', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
