# Generated by Django 4.2.1 on 2023-05-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='income_rate',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('salary', 'Salary')], max_length=100),
        ),
    ]
